[WIP] Type hash distribution during discovery (rep2011)
ros2/rmw_connextdds pull request #104
Opened 2023-02-23 22:54 UTC by emersonknapp

Part of 
Depends on

Distribute type hashes from introspection API using the USER_DATA Qos policy

2023-03-15 14:26 UTC, clalancette requested changes

2023-03-15 14:26 UTC, clalancette commented on rmw_connextdds_common/src/common/rmw_graph.cpp
> +    user_data_data, user_data_size);
This needs to be updated with the new API, and do error checking.

2023-03-15 14:26 UTC, clalancette commented on rmw_connextdds_common/src/common/rmw_impl.cpp
> +    *type_support->type_hash());
This needs to be updated with the new API and do error checking.  Also, let's not use `auto` here.

2023-03-16 02:24 UTC, emersonknapp commented on rmw_connextdds_common/src/common/rmw_graph.cpp
> +  const rosidl_type_hash_t * type_hash,
Changed to a const ref instead of ptr to obviate the need

2023-03-16 14:25 UTC, clalancette requested changes
Two small changes, this otherwise looks good to me.

2023-03-17 04:02 UTC, emersonknapp commented
Gist: https://gist.githubusercontent.com/emersonknapp/597121a37b82d9418b14472de760c8f0/raw/b0412d81c2ae2368cb592c810496d6f92650ad68/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11623
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18247)](http://ci.ros2.org/job/ci_linux/18247/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12780)](http://ci.ros2.org/job/ci_linux-aarch64/12780/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18921)](http://ci.ros2.org/job/ci_windows/18921/)

2023-03-17 12:09 UTC, clalancette approved these changes

2023-03-21 15:09 UTC, emersonknapp commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18261)](http://ci.ros2.org/job/ci_linux/18261/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12797)](http://ci.ros2.org/job/ci_linux-aarch64/12797/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18938)](http://ci.ros2.org/job/ci_windows/18938/)

2023-03-23 18:04 UTC, wjwwood approved these changes

2023-03-24 13:28 UTC, clalancette approved these changes

2023-03-26 12:44 UTC, clalancette commented
CI is in https://github.com/ros2/rmw_dds_common/pull/70#issuecomment-1483326412

2023-03-26 12:45 UTC, merged