Fix RMW_Connext_Client::is_service_available for micro
ros2/rmw_connextdds pull request #130
Opened 2023-08-03 06:29 UTC by cwecht

Fixed #128.

2023-08-03 13:07 UTC, clalancette requested changes
Can you please target this at the `rolling` branch first?  We can backport it from there.

2023-08-04 06:35 UTC, cwecht commented
rebase done.

2023-08-04 12:12 UTC, clalancette requested changes
One minor nit to fix, then I think this will be good to run CI on.

2023-08-07 06:28 UTC, cwecht commented on rmw_connextdds_common/src/common/rmw_impl.cpp
> +  available =  0 < this->request_pub->subscriptions_count() && 0 < this->reply_sub->publications_count();
Applied suggested fix and applied ament_uncrustify.

2023-08-07 13:35 UTC, clalancette approved these changes

2023-08-07 13:36 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19303)](http://ci.ros2.org/job/ci_linux/19303/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13834)](http://ci.ros2.org/job/ci_linux-aarch64/13834/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20023)](http://ci.ros2.org/job/ci_windows/20023/)

2023-08-07 20:47 UTC, merged